import Header from '@/app/components/header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, 'bg-[#F0F0EB] h-screen w-screen')}>
        <header className="font-normal text-[#29261b] text-base font-serif">
          <Header />
        </header>
        {children}
      </body>
    </html>
  )
}
